application: netskrafl
version: hummus
runtime: python27
api_version: 1
threadsafe: true

instance_class: F2
automatic_scaling:
  min_idle_instances: 2
  max_idle_instances: automatic
  min_pending_latency: 220ms
  max_pending_latency: 1250ms

inbound_services:
- warmup
- channel_presence

builtins:
- deferred: on

handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: 1d
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 1d
- url: /browserconfig.xml
  static_files: static/browserconfig.xml
  upload: static/browserconfig.xml
  expiration: 1d
- url: /apple-touch-icon.png
  static_files: static/touch-icon-ipad-retina.png
  upload: static/touch-icon-ipad-retina.png
  expiration: 1d
- url: /touch-icon-ipad.png
  static_files: static/touch-icon-ipad.png
  upload: static/touch-icon-ipad.png
  expiration: 1d
- url: /touch-icon-ipad-retina.png
  static_files: static/touch-icon-ipad-retina.png
  upload: static/touch-icon-ipad-retina.png
  expiration: 1d
- url: /touch-icon-iphone-retina.png
  static_files: static/touch-icon-iphone-retina.png
  upload: static/touch-icon-iphone-retina.png
  expiration: 1d
- url: /static/mousetrap.min.js
  static_files: static/mousetrap.min.js
  upload: static/mousetrap.min.js
  expiration: 1d
- url: /static/(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$
  expiration: 1d
- url: /static/skrafl-curry.css
  static_files: static/skrafl-curry.css
  upload: static/skrafl-curry.css
- url: /static/netskrafl.js
  static_files: static/netskrafl.js
  upload: static/netskrafl.js
- url: /static/jquery.ui.touch-punch.min.js
  static_files: static/jquery.ui.touch-punch.min.js
  upload: static/jquery.ui.touch-punch.min.js
  expiration: 1d
- url: /static/glyphicons-regular.ttf
  static_files: static/glyphicons-regular.ttf
  upload: static/glyphicons-regular.ttf
  expiration: 1d
  mime_type: application/font-sfnt
- url: /static/glyphicons-regular.eot
  static_files: static/glyphicons-regular.eot
  upload: static/glyphicons-regular.eot
  expiration: 1d
  mime_type: application/vnd.ms-fontobject
- url: /static/glyphicons-regular.svg
  static_files: static/glyphicons-regular.svg
  upload: static/glyphicons-regular.svg
  expiration: 1d
  mime_type: image/svg+xml
- url: /static/glyphicons-regular.woff
  static_files: static/glyphicons-regular.woff
  upload: static/glyphicons-regular.woff
  expiration: 1d
  mime_type: application/font-woff
- url: /static/(.*\.mp3)$
  static_files: static/\1
  upload: static/.*\.mp3$
  mime_type: audio/mpeg
  expiration: 1d
- url: /admin/.*
  script: netskrafl.app
  login: admin
  auth_fail_action: unauthorized
- url: .*
  script: netskrafl.app

skip_files:
- ^resources/.*\.txt$
- ^resources/.*\.dawg$
- ^(.*/)?.*\.psd$
- ^(.*/)?.*\.ai$
- ^(.*/)?.*\.log$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.bat$
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.tmp$
- ^(.*/)?.*\.TMP$
- ^(.*/)?.*\.less$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^\.git/.*$
- ^node_modules/.*$
- ^[gG]runtfile.js$
- ^(.*/)?\..*$
